### ISSUE TITLE
请教1个证书指纹问题

### ISSUE THREAD

**Issue by StarrySai** [Master-13/extract_ssl_certs#3]
小白请教。pcap里有证书指纹字段吗？为什么我没找到。您是如何计算证书指纹的？

**Comment by Master-13** [comment]
> 小白请教。pcap里有证书指纹字段吗？为什么我没找到。您是如何计算证书指纹的？

pyOpenSSL或者N多别的库，load证书之后，能读到指纹属性。但是指纹好像是不存在文件里的吧，应该是现算的

**Comment by StarrySai** [comment]
感谢。
